### ISSUE TITLE
Setup a "recommendation" algorithm using Spotify API.

### ISSUE THREAD

**Issue by jenniferlai43** [ucsb-cs56-f18/ucsb-cs56-recommend#2]
- [x] Implement a recommendation algorithm to find "similar" songs by using the Spotify API (likely querying by genre for MVP) based on user-inputted songs in the SQL database

**Comment by elizamr** [comment]
**Mentor Approved**
Estimate: ~350 points

*May need to break the second bullet point into other issues for MVP (i.e. implementing a simple query, displaying previously played songs, etc.)

* Note: Student requested more points due to sparse Spotify API documention / learning curve.

**Comment by elizamr** [comment]
Removed "Design UI" checkbox since the UI design is better suited as its own issue (Issue #3).

**Point Estimate for this issue is now 250.**
