### ISSUE TITLE
Create UI for viewing recommended songs

### ISSUE THREAD

**Issue by jenniferlai43** [ucsb-cs56-f18/ucsb-cs56-recommend#3]
- [x] Design a UI for viewing the recommended songs by a certain criteria

**Comment by elizamr** [comment]
**Mentor Approved**
Estimate: ~150 points

**Comment by elizamr** [comment]
**Mentor Approved**
Issue changed to meet MVP - adding songs only.
Estimate: ~200 points

**Comment by elizamr** [comment]
This issue overlaps with and is essentially a copy of Issue #2. Currently, 3 recommended songs are shown, and they all have the same genre.

**Comment by elizamr** [comment]
Removed "Design UI" checkbox from Issue #2. Since Issue #2 is marked as "Ready for QA" and originally included this issue, I moved this issue into "Ready for QA".

**Point estimate for this issue is now 150.**
