### ISSUE TITLE
Setup sorting algorithm for recommended songs.

### ISSUE THREAD

**Issue by shirlyntang** [ucsb-cs56-f18/ucsb-cs56-recommend#4]
- [ ] Implement a sorting algorithm (i.e. by genre, by artist, alphabetically) to display the recommended songs.

**Comment by elizamr** [comment]
**Mentor Approved**
Estimate: ~100 points

**Comment by shirlyntang** [comment]
Closing this issue because it's not in our MVP and we have decided to sort our recommendations only by genre.
