### ISSUE TITLE
Implement a button that will add the song to user's "playlist"

### ISSUE THREAD

**Issue by jenniferlai43** [ucsb-cs56-f18/ucsb-cs56-recommend#9]
- [x] Implement an "add to playlist" button that adds the recommended song to the existing database.

**Comment by elizamr** [comment]
Mentor Approved

Estimate: ~100 points

***Note:** This issue brings the total number of in progress/ready for QA issues to 1100.

**Comment by shirlyntang** [comment]
Issue solved with this pull request:
https://github.com/ucsb-cs56-webapps/ucsb-cs56-recommend/pull/3

**Comment by shao158** [comment]
Points are not awarded since when the add button is clicked, all recommended songs are added (While the user might need one).

Edit: It was my mistake. Points awarded now.
